# user-service port
server:
  port: 0 #random port 사용하겠다는 의미

spring:
  application:
    name: user-service

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    # 서버의 위치를 지정하는 것
    service-url:
      # 여기에 마이크로서비스 정보를 등록하겠다. eureka discovery-server가 기동중이어야 함
      defaultZone: http://127.0.0.1:8761/eureka
